name: Build_Subgen_Dockerfile_GPU

on:
  push:
  #  branches:
  #    - 'main'
  #  paths-ignore:
  #    - '**.md'
  #    - '**.yml'
    paths:
      - 'requirements.txt'
      - 'Dockerfile'
  workflow_dispatch:

jobs:
 
  docker:
    runs-on: ubuntu-latest

    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push GPU
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: jutze/subgen:latest
