name: Build_Subgen_Dockerfile_CPU

on:
  push:
  #  branches:
  #    - 'main'
  #  paths-ignore:
  #    - '**.md'
  #    - '**.yml'
     paths:
      - 'requirements.txt'
      - 'Dockerfile.cpu'
  workflow_dispatch:

jobs:
 
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push CPU
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64, linux/arm64
          file: ./Dockerfile.cpu
          push: true
          tags: jutze/subgen:cpu
